version: "3.7"

services:
  app:
    build: app
    image: akhng999/django-gunicorn
#    container_name: django-gunicorn
#    restart: always
    env_file:
      - django.env
    expose:
      - "8000"
    command:
      "gunicorn --workers=2 --bind=0.0.0.0:8000 mysite.wsgi:application"

  nginx:
    build: nginx
    image: akhng999/nginx:ngx-appprotect
    container_name: ngx-appprotect
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
